/* @pjs preload=
"img/bg1.png,
img/bg2.png,
img/end1.png,
img/end2.png,
img/enemy.png,
img/enemy2.png,
img/fighter.png,
img/flame1.png,
img/flame2.png,
img/flame3.png,
img/flame4.png,
img/flame5.png,
img/hp.png,
img/shoot.png,
img/start1.png,
img/start2.png,
img/treasure.png"; */